/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

/**
 *
 * @author EDVALDO
 */
public class TelaPrincipalAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaPrincipalAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCliente = new javax.swing.JInternalFrame();
        painel = new javax.swing.JPanel();
        painelAcoes = new javax.swing.JPanel();
        btnAdicionaCliente = new javax.swing.JButton();
        btnEditCliente = new javax.swing.JButton();
        btnRemoveCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBarraPesquisaCliente = new javax.swing.JTextField();
        btnPesquisaCliente = new javax.swing.JButton();
        btnSaiCliente = new javax.swing.JButton();
        scrollCliente = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        addFornecedor = new javax.swing.JInternalFrame();
        painel1 = new javax.swing.JPanel();
        painelAcoes1 = new javax.swing.JPanel();
        btnAdicionaFornecedor = new javax.swing.JButton();
        btnEditFornecedor = new javax.swing.JButton();
        btnRemoveFornecedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBarraPesquisaFornecedor = new javax.swing.JTextField();
        btnPesquisaFornecedor = new javax.swing.JButton();
        btnSaiFornecedor = new javax.swing.JButton();
        scrollFornecedor = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        addProduto = new javax.swing.JInternalFrame();
        painel2 = new javax.swing.JPanel();
        painelAcoes2 = new javax.swing.JPanel();
        btnAdicionaProduto = new javax.swing.JButton();
        btnEditProduto = new javax.swing.JButton();
        btnRemoveProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBarraPesquisaCodigo = new javax.swing.JTextField();
        btnPesquisaProduto = new javax.swing.JButton();
        btnSaiProduto = new javax.swing.JButton();
        scrollProduto = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        MenuBarra = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        mnItemCliente = new javax.swing.JMenuItem();
        mnItemFornecedor = new javax.swing.JMenuItem();
        MenuProduto = new javax.swing.JMenu();
        mnItemProduto = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        mnItemSobre = new javax.swing.JMenuItem();
        mnItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        addCliente.setTitle("Cliente");
        addCliente.setVisible(false);
        addCliente.getContentPane().setLayout(new javax.swing.OverlayLayout(addCliente.getContentPane()));

        painelAcoes.setLayout(new javax.swing.BoxLayout(painelAcoes, javax.swing.BoxLayout.LINE_AXIS));

        btnAdicionaCliente.setText("Adicionar");
        btnAdicionaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaClienteActionPerformed(evt);
            }
        });
        painelAcoes.add(btnAdicionaCliente);

        btnEditCliente.setText("Editar");
        painelAcoes.add(btnEditCliente);

        btnRemoveCliente.setText("Remover");
        painelAcoes.add(btnRemoveCliente);

        jLabel3.setText("Pesquisa Por Nome");
        painelAcoes.add(jLabel3);
        painelAcoes.add(txtBarraPesquisaCliente);

        btnPesquisaCliente.setText("Ok");
        painelAcoes.add(btnPesquisaCliente);

        btnSaiCliente.setText("Sair");
        btnSaiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaiClienteActionPerformed(evt);
            }
        });
        painelAcoes.add(btnSaiCliente);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollCliente.setViewportView(tblClientes);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addComponent(scrollCliente)
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addComponent(painelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addCliente.getContentPane().add(painel);

        getContentPane().add(addCliente);

        addFornecedor.setTitle("Fornecedor");
        addFornecedor.setVisible(false);
        addFornecedor.getContentPane().setLayout(new javax.swing.OverlayLayout(addFornecedor.getContentPane()));

        painelAcoes1.setLayout(new javax.swing.BoxLayout(painelAcoes1, javax.swing.BoxLayout.LINE_AXIS));

        btnAdicionaFornecedor.setText("Adicionar");
        btnAdicionaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaFornecedorActionPerformed(evt);
            }
        });
        painelAcoes1.add(btnAdicionaFornecedor);

        btnEditFornecedor.setText("Editar");
        painelAcoes1.add(btnEditFornecedor);

        btnRemoveFornecedor.setText("Remover");
        painelAcoes1.add(btnRemoveFornecedor);

        jLabel4.setText("Pesquisa Por Nome");
        painelAcoes1.add(jLabel4);
        painelAcoes1.add(txtBarraPesquisaFornecedor);

        btnPesquisaFornecedor.setText("Ok");
        painelAcoes1.add(btnPesquisaFornecedor);

        btnSaiFornecedor.setText("Sair");
        btnSaiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaiFornecedorActionPerformed(evt);
            }
        });
        painelAcoes1.add(btnSaiFornecedor);

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollFornecedor.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAcoes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addComponent(painelAcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addFornecedor.getContentPane().add(painel1);

        getContentPane().add(addFornecedor);

        addProduto.setTitle("Produto");
        addProduto.setVisible(false);
        addProduto.getContentPane().setLayout(new javax.swing.OverlayLayout(addProduto.getContentPane()));

        painelAcoes2.setLayout(new javax.swing.BoxLayout(painelAcoes2, javax.swing.BoxLayout.LINE_AXIS));

        btnAdicionaProduto.setText("Adicionar");
        btnAdicionaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaProdutoActionPerformed(evt);
            }
        });
        painelAcoes2.add(btnAdicionaProduto);

        btnEditProduto.setText("Editar");
        painelAcoes2.add(btnEditProduto);

        btnRemoveProduto.setText("Remover");
        painelAcoes2.add(btnRemoveProduto);

        jLabel5.setText("Pesquisa Por Código");
        painelAcoes2.add(jLabel5);
        painelAcoes2.add(txtBarraPesquisaCodigo);

        btnPesquisaProduto.setText("Ok");
        painelAcoes2.add(btnPesquisaProduto);

        btnSaiProduto.setText("Sair");
        btnSaiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaiProdutoActionPerformed(evt);
            }
        });
        painelAcoes2.add(btnSaiProduto);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollProduto.setViewportView(tblProdutos);

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAcoes2, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addComponent(scrollProduto)
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addComponent(painelAcoes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addProduto.getContentPane().add(painel2);

        getContentPane().add(addProduto);

        MenuCadastro.setText("Cadastro");

        mnItemCliente.setText("Cliente");
        mnItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(mnItemCliente);

        mnItemFornecedor.setText("Fornecedor");
        mnItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemFornecedorActionPerformed(evt);
            }
        });
        MenuCadastro.add(mnItemFornecedor);

        MenuBarra.add(MenuCadastro);

        MenuProduto.setText("Produto");

        mnItemProduto.setText("Cadastro/Estoque");
        mnItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemProdutoActionPerformed(evt);
            }
        });
        MenuProduto.add(mnItemProduto);

        MenuBarra.add(MenuProduto);

        MenuAjuda.setText("Ajuda");

        mnItemSobre.setText("Sobre");
        MenuAjuda.add(mnItemSobre);

        mnItemSair.setText("Sair");
        mnItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSairActionPerformed(evt);
            }
        });
        MenuAjuda.add(mnItemSair);

        MenuBarra.add(MenuAjuda);

        setJMenuBar(MenuBarra);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_mnItemSairActionPerformed

    private void mnItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemClienteActionPerformed
        addCliente.setVisible(true);
        addFornecedor.setVisible(false);
        addProduto.setVisible(false);
    }//GEN-LAST:event_mnItemClienteActionPerformed

    private void mnItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemFornecedorActionPerformed
        addFornecedor.setVisible(true);
        addCliente.setVisible(false);
        addProduto.setVisible(false);
    }//GEN-LAST:event_mnItemFornecedorActionPerformed

    private void btnAdicionaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaClienteActionPerformed
        TelaCadastroCliente tela = new TelaCadastroCliente(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionaClienteActionPerformed

    private void btnAdicionaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaFornecedorActionPerformed
        TelaCadastroFornecedor tela = new TelaCadastroFornecedor(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionaFornecedorActionPerformed

    private void btnAdicionaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaProdutoActionPerformed
        TelaCadastroProduto tela = new TelaCadastroProduto(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionaProdutoActionPerformed

    private void mnItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemProdutoActionPerformed
        addProduto.setVisible(true);
        addCliente.setVisible(false);
        addFornecedor.setVisible(false);
    }//GEN-LAST:event_mnItemProdutoActionPerformed

    private void btnSaiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaiClienteActionPerformed
        addCliente.setVisible(false);
    }//GEN-LAST:event_btnSaiClienteActionPerformed

    private void btnSaiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaiFornecedorActionPerformed
        addFornecedor.setVisible(false);
    }//GEN-LAST:event_btnSaiFornecedorActionPerformed

    private void btnSaiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaiProdutoActionPerformed
        addProduto.setVisible(false);
    }//GEN-LAST:event_btnSaiProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuProduto;
    private javax.swing.JInternalFrame addCliente;
    private javax.swing.JInternalFrame addFornecedor;
    private javax.swing.JInternalFrame addProduto;
    private javax.swing.JButton btnAdicionaCliente;
    private javax.swing.JButton btnAdicionaFornecedor;
    private javax.swing.JButton btnAdicionaProduto;
    private javax.swing.JButton btnEditCliente;
    private javax.swing.JButton btnEditFornecedor;
    private javax.swing.JButton btnEditProduto;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaFornecedor;
    private javax.swing.JButton btnPesquisaProduto;
    private javax.swing.JButton btnRemoveCliente;
    private javax.swing.JButton btnRemoveFornecedor;
    private javax.swing.JButton btnRemoveProduto;
    private javax.swing.JButton btnSaiCliente;
    private javax.swing.JButton btnSaiFornecedor;
    private javax.swing.JButton btnSaiProduto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem mnItemCliente;
    private javax.swing.JMenuItem mnItemFornecedor;
    private javax.swing.JMenuItem mnItemProduto;
    private javax.swing.JMenuItem mnItemSair;
    private javax.swing.JMenuItem mnItemSobre;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painelAcoes;
    private javax.swing.JPanel painelAcoes1;
    private javax.swing.JPanel painelAcoes2;
    private javax.swing.JScrollPane scrollCliente;
    private javax.swing.JScrollPane scrollFornecedor;
    private javax.swing.JScrollPane scrollProduto;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBarraPesquisaCliente;
    private javax.swing.JTextField txtBarraPesquisaCodigo;
    private javax.swing.JTextField txtBarraPesquisaFornecedor;
    // End of variables declaration//GEN-END:variables
}
